spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sectors
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
